/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * Public HTML/ISR caching is handled by vinext's CDN cache adapter
 * (configured in vite.config.ts). This worker keeps project-specific
 * concerns: image optimization, trailing-slash canonicalization, and cron.
 *
 * Foundation-routed requests (health, storage, notion media) are
 * handled by `createFoundationWorker` before falling through to the
 * vinext handler. Foundation returns `null` for unhandled paths so
 * the rest of the logic (image opt, perf logging, canonicalization,
 * the cron handler) is preserved exactly as before.
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
  isImageOptimizationPath,
} from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { createFoundationWorker } from "@vinext/foundation/worker";
import { authConfig } from "../lib/auth.config";
import { adminNav } from "../lib/admin/nav";
import { siteConfig } from "../lib/site/config";
import { blogContentModel, movieContentModel } from "../lib/content/models";
import { prewarmPublicContentSearchIndex } from "../lib/content/prewarm";
import { defaultLocale, supportedLocales } from "../lib/i18n/config";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface ScheduledController {
  cron: string;
  scheduledTime: number;
  noRetry(): void;
}

const PUBLIC_CONTENT_RE = /^\/(?:blog|movies)(?:\/[^/]+)?\/?$/;

const foundation = createFoundationWorker({
  sources: [blogContentModel, movieContentModel],
  adminNav,
  authConfig,
  siteConfig: {
    name: siteConfig.name,
    description: siteConfig.description,
    defaultLocale,
    locales: [...supportedLocales],
    navigation: siteConfig.navigation.main as unknown as unknown[],
  },
});

type PageClass =
  | "home"
  | "blog_list"
  | "blog_detail"
  | "movie_list"
  | "movie_detail"
  | "admin"
  | "auth"
  | "api"
  | "image"
  | "asset"
  | "other";

function classifyPath(pathname: string): PageClass {
  if (pathname === "/" || pathname === "") return "home";
  if (/^\/blog(?:\/[^/]+)?\/?$/.test(pathname)) {
    return pathname === "/blog" || pathname === "/blog/" ? "blog_list" : "blog_detail";
  }
  if (/^\/[^/]+\/movies(?:\/[^/]+)?\/?$/.test(pathname)) {
    return /\/movies\/?$/.test(pathname) ? "movie_list" : "movie_detail";
  }
  if (pathname.startsWith("/admin")) return "admin";
  if (
    pathname.startsWith("/login") ||
    pathname.startsWith("/register") ||
    pathname.startsWith("/logout")
  ) {
    return "auth";
  }
  if (pathname.startsWith("/api/") || pathname === "/api") return "api";
  if (
    pathname.startsWith("/_next/") ||
    pathname === "/favicon.ico" ||
    pathname === "/robots.txt" ||
    pathname === "/sitemap.xml"
  ) {
    return "asset";
  }
  if (isImageOptimizationPath(pathname)) return "image";
  return "other";
}

function perfLog(fields: Record<string, unknown>) {
  try {
    console.log(JSON.stringify({ tag: "perf", ts: Date.now(), ...fields }));
  } catch {
    // Ignore serialization errors.
  }
}

function stripTrailingSlash(pathname: string): string {
  if (pathname.length > 1 && pathname.endsWith("/")) {
    return pathname.slice(0, -1);
  }
  return pathname;
}

function canonicalizePublicContentRequest(request: Request): Request {
  if (request.method !== "GET") return request;

  const url = new URL(request.url);
  if (!PUBLIC_CONTENT_RE.test(url.pathname)) return request;

  const canonicalPath = stripTrailingSlash(url.pathname);
  if (canonicalPath === url.pathname) return request;

  const rewritten = new URL(request.url);
  rewritten.pathname = canonicalPath;
  return new Request(rewritten, request);
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const t0 = performance.now();
    const pageClass = classifyPath(url.pathname);
    let branch = "delegate";
    const willTrace = request.method === "GET" || request.method === "POST";
    const effectiveRequest = canonicalizePublicContentRequest(request);
    const effectiveUrl = new URL(effectiveRequest.url);

    if (isImageOptimizationPath(url.pathname)) {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      const response = await handleImageOptimization(
        request,
        {
          fetchAsset: (path) =>
            env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths
      );
      branch = "image_optimization";
      if (willTrace) {
        perfLog({
          kind: "page",
          page_class: "image",
          method: request.method,
          path: url.pathname,
          status: response.status,
          branch,
          duration_ms: round(performance.now() - t0),
        });
      }
      return response;
    }

    // Ask foundation first. It returns `null` when no foundation route
    // matches, in which case we fall through to the vinext handler.
    const foundationResponse = await foundation.fetch(request, env, ctx);
    if (foundationResponse) {
      branch = "foundation";
      if (willTrace) {
        perfLog({
          kind: "page",
          page_class: "api",
          method: request.method,
          path: url.pathname,
          status: foundationResponse.status,
          branch,
          duration_ms: round(performance.now() - t0),
        });
      }
      return foundationResponse;
    }

    const tDelegate = performance.now();
    const response = await handler.fetch(effectiveRequest, env, ctx);
    const delegateMs = round(performance.now() - tDelegate);

    if (
      willTrace &&
      effectiveUrl.pathname !== url.pathname &&
      PUBLIC_CONTENT_RE.test(effectiveUrl.pathname)
    ) {
      branch = "canonicalized_delegate";
    }

    if (willTrace) {
      perfLog({
        kind: "page",
        page_class: pageClass,
        method: request.method,
        path: effectiveUrl.pathname,
        status: response.status,
        branch,
        render_ms: delegateMs,
        duration_ms: round(performance.now() - t0),
      });
    }

    return response;
  },

  async scheduled(
    controller: ScheduledController,
    _env: Env,
    _ctx: ExecutionContext
  ): Promise<void> {
    try {
      const result = await prewarmPublicContentSearchIndex();
      console.log(
        JSON.stringify({
          tag: "scheduled_content_prewarm",
          cron: controller.cron,
          scheduled_time: controller.scheduledTime,
          ok: result.ok,
          duration_ms: result.durationMs,
          models: result.models,
        })
      );
    } catch (error) {
      controller.noRetry();
      console.error(
        JSON.stringify({
          tag: "scheduled_content_prewarm_error",
          cron: controller.cron,
          scheduled_time: controller.scheduledTime,
          message: error instanceof Error ? error.message : String(error),
        })
      );
    }
  },
};

function round(n: number): number {
  return Math.round(n * 100) / 100;
}
