import type { Answers } from "./prompt.js";

export const SCAFFOLD_METADATA_FILE = ".notionx/scaffold.json";

export interface ScaffoldMetadata {
  projectKind: "notionx";
  projectName: string;
  scaffoldVersion: string;
  defaultLocale: string;
  supportedLocales: string[];
  notionxSource: string;
  enableSiteSettings: boolean;
  contentSource: {
    id: string;
    title: string;
    fields: Answers["contentSource"]["fields"];
  };
  /**
   * Optional compatibility mode for projects that predate (or are
   * upstream of) a particular scaffolder version. Today only one
   * value is recognised:
   *
   *   "legacy-vinext" — the project was authored by hand (or
   *   copied from an earlier workspace) rather than generated by
   *   this scaffolder. The scaffolder's `update` command must
   *   preserve `@notionx/core`'s `workspace:*` protocol even if
   *   the user runs an explicit update, and must not re-render
   *   `wrangler.jsonc` from a generic template (which would wipe
   *   custom bindings like a different D1 binding name).
   *
   * Absent or any other value means "this project is a normal
   * scaffolder consumer" and the update flow runs as before.
   */
  compatibility?: "legacy-vinext" | string;
  /**
   * Optional project-specific extras (custom lib modules,
   * non-templated app routes, binding names). The scaffolder
   * never writes or rewrites this block — it is a
   * hand-maintained hint that survives update runs. Tools like
   * the doctor and the provision-repair command read it to
   * skip files that they otherwise would have flagged.
   */
  extras?: Record<string, unknown>;
  /**
   * Maps a built-in translation source name (or content source id)
   * to the Notion data source that holds its locale-specific rows.
   * The scaffolder never writes or rewrites this block on a normal
   * update run; the `notionx locale add` command manages it.
   */
  translationSources?: Record<string, TranslationSourceRef>;
}

export interface TranslationSourceRef {
  dataSourceId: string;
  envVar: string;
}

export function buildScaffoldMetadata(
  answers: Answers,
  scaffoldVersion: string
): ScaffoldMetadata {
  return {
    projectKind: "notionx",
    projectName: answers.projectName,
    scaffoldVersion,
    defaultLocale: answers.defaultLocale,
    supportedLocales: [...answers.supportedLocales],
    notionxSource: answers.notionxSource,
    enableSiteSettings: answers.enableSiteSettings,
    contentSource: {
      id: answers.contentSource.id,
      title: answers.contentSource.title,
      fields: answers.contentSource.fields.map((field) => ({
        key: field.key,
        notionName: field.notionName,
      })),
    },
    translationSources: {},
  };
}

export function parseScaffoldMetadata(raw: string): ScaffoldMetadata {
  const parsed = JSON.parse(raw) as Partial<ScaffoldMetadata>;
  if (
    parsed.projectKind !== "notionx" ||
    typeof parsed.projectName !== "string" ||
    typeof parsed.scaffoldVersion !== "string" ||
    typeof parsed.defaultLocale !== "string" ||
    !Array.isArray(parsed.supportedLocales) ||
    typeof parsed.notionxSource !== "string" ||
    !parsed.contentSource ||
    typeof parsed.contentSource.id !== "string" ||
    typeof parsed.contentSource.title !== "string" ||
    !Array.isArray(parsed.contentSource.fields) ||
    parsed.contentSource.fields.some(
      (field) =>
        !field ||
        typeof field.key !== "string" ||
        typeof field.notionName !== "string"
    )
  ) {
    throw new Error("Invalid Notionx metadata payload");
  }

  return parsed as ScaffoldMetadata;
}
