/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES, isImageOptimizationPath } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { publicApiCacheKeyForUrl, publicCacheKey } from "../lib/cache-keys";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// 仅缓存"不读 cookies / 不分用户态"的公开页面。
// 路径白名单：博客和电影库的公开列表与详情。
// 本 Worker 是公开页 HTML 的"单一主缓存层"：发布/审核/更新时由 lib/actions.ts
// 触发 cache.delete(publicCacheKey(...))，不再依赖 ISR 被动过期。
const PUBLIC_CONTENT_RE = /^\/(?:blog|movies)(?:\/[^/]+)?\/?$/;
const PUBLIC_API_RE = /^\/api\/(?:posts(?:\/[^/]+)?|movies(?:\/[^/]+)?)\/?$/;
const PUBLIC_HTML_CACHE_CONTROL =
  "public, max-age=0, s-maxage=300, stale-while-revalidate=600";
const PUBLIC_API_CACHE_CONTROL =
  "public, max-age=0, s-maxage=300, stale-while-revalidate=600";

// 页面分类（用于 traces/logs 上按 page_class 过滤）
type PageClass = "home" | "blog_list" | "blog_detail" | "movie_list" | "movie_detail" | "admin" | "auth" | "api" | "image" | "asset" | "other";
function classifyPath(pathname: string): PageClass {
  if (pathname === "/" || pathname === "") return "home";
  if (/^\/blog(?:\/[^/]+)?\/?$/.test(pathname)) {
    // /blog 自身是 list，/blog/<slug> 是 detail
    return pathname === "/blog" || pathname === "/blog/" ? "blog_list" : "blog_detail";
  }
  if (/^\/movies(?:\/[^/]+)?\/?$/.test(pathname)) {
    return pathname === "/movies" || pathname === "/movies/" ? "movie_list" : "movie_detail";
  }
  if (pathname.startsWith("/admin")) return "admin";
  if (pathname.startsWith("/login") || pathname.startsWith("/register") || pathname.startsWith("/logout")) return "auth";
  if (pathname.startsWith("/api/") || pathname === "/api") return "api";
  if (pathname.startsWith("/_next/") || pathname === "/favicon.ico" || pathname === "/robots.txt" || pathname === "/sitemap.xml") return "asset";
  if (isImageOptimizationPath(pathname)) return "image";
  return "other";
}

// 结构化日志：每行一个 kind=...，便于 Cloudflare Logs / Traces / Query Builder 直接过滤
// 关键字段：kind, page_class, method, path, status, branch, duration_ms
function perfLog(fields: Record<string, unknown>) {
  // 用 console.log + 紧凑 JSON，避免 splat 占位让 Cloudflare Logs 把消息打散
  try {
    console.log(JSON.stringify({ tag: "perf", ts: Date.now(), ...fields }));
  } catch {
    // 忽略序列化错误
  }
}

// 在调用 vinext 之前把 trailing-slash 路径内部改写为 canonical 形式，
// 避免 vinext 默认 308（`/blog/` -> `/blog`）带来的额外 RTT 与缓存碎片。
// 仅对公开博客路径生效，其它路径仍交给 vinext 自己处理以保持兼容。
function stripTrailingSlash(pathname: string): string {
  if (pathname.length > 1 && pathname.endsWith("/")) {
    return pathname.slice(0, -1);
  }
  return pathname;
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    const t0 = performance.now();
    const pageClass = classifyPath(url.pathname);
    let branch: string = "delegate";
    let cacheMode: string | undefined;
    const willTrace = request.method === "GET" || request.method === "POST";

    // 1) 公开内容路径：先做 trailing-slash 改写，再决定是否走缓存
    let effectiveRequest = request;
    if (
      request.method === "GET" &&
      (PUBLIC_CONTENT_RE.test(url.pathname) || PUBLIC_API_RE.test(url.pathname))
    ) {
      const canonicalPath = stripTrailingSlash(url.pathname);
      if (canonicalPath !== url.pathname) {
        const rewritten = new URL(request.url);
        rewritten.pathname = canonicalPath;
        effectiveRequest = new Request(rewritten, request);
      }
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (isImageOptimizationPath(url.pathname)) {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      const r = await handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
      branch = "image_optimization";
      if (willTrace) perfLog({ kind: "page", page_class: "image", method: request.method, path: url.pathname, status: r.status, branch, duration_ms: round(performance.now() - t0) });
      return r;
    }

    // 公开内容页：走 Cloudflare 边缘 PoP 缓存（caches.default）
    // - 仅缓存 HTML 响应（Accept: text/html）
    // - 排除 RSC 内部端点（_rsc=, RSC 头）
    // - 强制覆盖 Cache-Control 让 CF 接受
    // - 使用 *最小化* Vary，让 CF 边缘 PoP 能真正复用
    const effectiveUrl = new URL(effectiveRequest.url);
    if (
      effectiveRequest.method === "GET" &&
      PUBLIC_CONTENT_RE.test(effectiveUrl.pathname) &&
      !effectiveUrl.searchParams.has("_rsc") &&
      (effectiveRequest.headers.get("accept") ?? "").includes("text/html")
    ) {
      const cache = (caches as CacheStorage & { default: Cache }).default;
      const cacheKey = new Request(publicCacheKey(effectiveUrl.pathname), { method: "GET" });
      const cached = await cache.match(cacheKey);
      if (cached) {
        // 命中：直接返回 + 标记 HIT
        const headers = new Headers(cached.headers);
        headers.set("Cache-Control", PUBLIC_HTML_CACHE_CONTROL);
        headers.set("Vary", "Accept-Encoding");
        headers.set("X-Public-Page-Cache", "HIT");
        // #region debug-point A:public-cache-hit
        headers.set("X-Debug-Public-Cache", "eligible-hit");
        headers.set("X-Debug-Public-Path", effectiveUrl.pathname);
        // #endregion
        branch = "public_cache_hit";
        cacheMode = "HIT";
        const response = new Response(cached.body, { status: cached.status, headers });
        if (willTrace) perfLog({ kind: "page", page_class: classifyPath(effectiveUrl.pathname), method: request.method, path: effectiveUrl.pathname, status: cached.status, branch, cache: cacheMode, duration_ms: round(performance.now() - t0) });
        return response;
      }

      // Miss：调用 vinext handler 渲染
      const tRender = performance.now();
      const response = await handler.fetch(effectiveRequest, env, ctx);
      const renderMs = round(performance.now() - tRender);
      // 仅缓存 200 + HTML
      const ctype = response.headers.get("content-type") ?? "";
      if (response.status === 200 && ctype.includes("text/html")) {
        const cloned = response.clone();
        const headers = new Headers(cloned.headers);
        headers.set("Cache-Control", PUBLIC_HTML_CACHE_CONTROL);
        // 显式把 Vary 收敛为最窄集合，避免 CF 边缘因 RSC 内部 vary 拒绝复用
        headers.set("Vary", "Accept-Encoding");
        headers.set("X-Public-Page-Cache", "MISS");
        // #region debug-point A:public-cache-miss
        headers.set("X-Debug-Public-Cache", "eligible-miss-html");
        headers.set("X-Debug-Public-Path", effectiveUrl.pathname);
        // #endregion
        const toCache = new Response(cloned.body, {
          status: cloned.status,
          headers,
        });
        // 异步写缓存，不阻塞响应
        ctx.waitUntil(cache.put(cacheKey, toCache));
        branch = "public_cache_miss";
        cacheMode = "MISS";
        const out = new Response(response.body, {
          status: response.status,
          headers,
        });
        if (willTrace) perfLog({ kind: "page", page_class: classifyPath(effectiveUrl.pathname), method: request.method, path: effectiveUrl.pathname, status: response.status, branch, cache: cacheMode, render_ms: renderMs, duration_ms: round(performance.now() - t0) });
        return out;
      }
      // #region debug-point A:public-cache-bypass
      const bypassHeaders = new Headers(response.headers);
      bypassHeaders.set("X-Debug-Public-Cache", "eligible-bypass-non-html");
      bypassHeaders.set("X-Debug-Public-Path", effectiveUrl.pathname);
      // #endregion
      branch = "public_cache_bypass";
      if (willTrace) perfLog({ kind: "page", page_class: classifyPath(effectiveUrl.pathname), method: request.method, path: effectiveUrl.pathname, status: response.status, branch, render_ms: renderMs, duration_ms: round(performance.now() - t0) });
      return new Response(response.body, { status: response.status, headers: bypassHeaders });
    }

    // 公开 JSON API：同样走 Cloudflare 边缘缓存。这里只匹配公开内容接口，
    // 不包含 /api/movies/:id/download 这类需要登录态的私密接口。
    if (
      effectiveRequest.method === "GET" &&
      PUBLIC_API_RE.test(effectiveUrl.pathname)
    ) {
      const cache = (caches as CacheStorage & { default: Cache }).default;
      const cacheKey = new Request(publicApiCacheKeyForUrl(effectiveUrl), { method: "GET" });
      const cached = await cache.match(cacheKey);
      if (cached) {
        const headers = new Headers(cached.headers);
        headers.set("Cache-Control", PUBLIC_API_CACHE_CONTROL);
        headers.set("Vary", "Accept-Encoding");
        headers.set("X-Public-API-Cache", "HIT");
        branch = "public_api_cache_hit";
        cacheMode = "HIT";
        const response = new Response(cached.body, { status: cached.status, headers });
        if (willTrace) perfLog({ kind: "page", page_class: "api", method: request.method, path: effectiveUrl.pathname, status: cached.status, branch, cache: cacheMode, duration_ms: round(performance.now() - t0) });
        return response;
      }

      const tRender = performance.now();
      const response = await handler.fetch(effectiveRequest, env, ctx);
      const renderMs = round(performance.now() - tRender);
      const ctype = response.headers.get("content-type") ?? "";
      if (response.status === 200 && ctype.includes("application/json")) {
        const cloned = response.clone();
        const headers = new Headers(cloned.headers);
        headers.set("Cache-Control", PUBLIC_API_CACHE_CONTROL);
        headers.set("Vary", "Accept-Encoding");
        headers.set("X-Public-API-Cache", "MISS");
        const toCache = new Response(cloned.body, {
          status: cloned.status,
          headers,
        });
        ctx.waitUntil(cache.put(cacheKey, toCache));
        branch = "public_api_cache_miss";
        cacheMode = "MISS";
        const out = new Response(response.body, {
          status: response.status,
          headers,
        });
        if (willTrace) perfLog({ kind: "page", page_class: "api", method: request.method, path: effectiveUrl.pathname, status: response.status, branch, cache: cacheMode, render_ms: renderMs, duration_ms: round(performance.now() - t0) });
        return out;
      }

      const headers = new Headers(response.headers);
      headers.set("X-Public-API-Cache", "BYPASS");
      branch = "public_api_cache_bypass";
      if (willTrace) perfLog({ kind: "page", page_class: "api", method: request.method, path: effectiveUrl.pathname, status: response.status, branch, render_ms: renderMs, duration_ms: round(performance.now() - t0) });
      return new Response(response.body, { status: response.status, headers });
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    const tDelegate = performance.now();
    const response = await handler.fetch(effectiveRequest, env, ctx);
    const delegateMs = round(performance.now() - tDelegate);
    branch = "delegate";
    if (willTrace) perfLog({ kind: "page", page_class: pageClass, method: request.method, path: url.pathname, status: response.status, branch, render_ms: delegateMs, duration_ms: round(performance.now() - t0) });
    return response;
  },
};

function round(n: number): number {
  return Math.round(n * 100) / 100;
}
