import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    types: "src/types.ts",
    "util/index": "src/util/index.ts",
    "i18n/index": "src/i18n/index.ts",
    "platform/index": "src/platform/index.ts",
    "platform/current": "src/platform/current.ts",
    "platform/runtime": "src/platform/runtime.ts",
    "platform/selection": "src/platform/selection.ts",
    "platform/capabilities": "src/platform/capabilities.ts",
    "cache/index": "src/cache/index.ts",
    "pages/index": "src/pages/index.ts",
    "notion/index": "src/notion/index.ts",
    "notion/client": "src/notion/client.ts",
    "notion/config": "src/notion/config.ts",
    "notion/blocks": "src/notion/blocks.ts",
    "notion/block-text": "src/notion/block-text.ts",
    "notion/content-cache": "src/notion/content-cache.ts",
    "notion/media": "src/notion/media.ts",
    "notion/generic-source": "src/notion/generic-source.ts",
    "notion/property-mappers": "src/notion/property-mappers.ts",
    "notion/types": "src/notion/types.ts",
    "notion/webhook": "src/notion/webhook.ts",
    "notion/mappers": "src/notion/mappers.ts",
    "content/index": "src/content/index.ts",
    "content/models": "src/content/models.ts",
    "content/revalidate": "src/content/revalidate.ts",
    "content/search": "src/content/search.ts",
    "content/search-index": "src/content/search-index.ts",
    "content/prewarm": "src/content/prewarm.ts",
    "content/localized": "src/content/localized.ts",
    "content/admin-summary": "src/content/admin-summary.ts",
    "search/index": "src/search/index.ts",
    "search/adapter": "src/search/adapter.ts",
    "auth/index": "src/auth/index.ts",
    "auth/session": "src/auth/session.ts",
    "auth/passwords": "src/auth/passwords.ts",
    "auth/rate-limit": "src/auth/rate-limit.ts",
    "auth/users": "src/auth/users.ts",
    "auth/turnstile": "src/auth/turnstile.ts",
    "auth/user-session": "src/auth/user-session.ts",
    "auth/auth-pages/index": "src/auth/auth-pages/index.ts",
    "auth/auth-pages/login": "src/auth/auth-pages/login.tsx",
    "auth/auth-pages/register": "src/auth/auth-pages/register.tsx",
    "auth/auth-pages/forgot-password": "src/auth/auth-pages/forgot-password.tsx",
    "auth/auth-pages/reset-password": "src/auth/auth-pages/reset-password.tsx",
    "auth/routes/index": "src/auth/routes/index.ts",
    "auth/routes/google": "src/auth/routes/google.ts",
    "auth/routes/google-callback": "src/auth/routes/google-callback.ts",
    "auth/routes/verify-email": "src/auth/routes/verify-email.ts",
    "auth/routes/viewer": "src/auth/routes/viewer.ts",
    "storage/index": "src/storage/index.ts",
    "storage/routes/index": "src/storage/routes/index.ts",
    "storage/routes/files": "src/storage/routes/files.ts",
    "storage/routes/cdn": "src/storage/routes/cdn.ts",
    "media/index": "src/media/index.ts",
    "media/routes/index": "src/media/routes/index.ts",
    "media/routes/notion-media": "src/media/routes/notion-media.ts",
    "notion/routes/index": "src/notion/routes/index.ts",
    "notion/routes/webhook": "src/notion/routes/webhook.ts",
    "email/index": "src/email/index.ts",
    "admin/index": "src/admin/index.ts",
    "admin/pages/index": "src/admin/pages/index.ts",
    "internal/admin/index": "src/internal/admin/index.ts",
    "doctor/index": "src/doctor/index.ts",
    "doctor/cli": "src/doctor/cli.ts",
    "worker/index": "src/worker/index.ts",
    "middleware": "src/middleware.ts",
    "worker/routes/index": "src/worker/routes/index.ts",
    "worker/routes/health": "src/worker/routes/health.ts",
    "worker/routes/content-revalidate": "src/worker/routes/content-revalidate.ts",
    "worker/routes/content-prewarm": "src/worker/routes/content-prewarm.ts",
    "worker/routes/search": "src/worker/routes/search.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  target: "es2022",
  // Virtual modules and consumer runtime modules must not be bundled.
  // Consumers (the starter) resolve these at runtime in Cloudflare Workers
  // or in the vinext/Next.js runtime.
  external: [
    "cloudflare:workers",
    /^next\//,
    /^react($|\/)/,
    /^react-dom($|\/)/,
    "lucide-react",
    "vinext/shims/request-context",
  ],
});
